apiVersion : apps/v1
kind: Deployment
metadata:
  name: moviebookingapplatest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviebookingapplatest
  template:
    metadata:
      labels:
        app: moviebookingapplatest 
    spec:
      containers:
        - name: moviebookingapplatest 
          image: myfirstapplicationazureregistry.azurecr.io/moviebookingapplatest
          ports:
          - containerPort: 8090